### PR TITLE
fix: make sure handler is resolvable

### LINKED ISSUE #179: `handler()` does not always resolve, causing memory leak
In a normal usage with API Routes, there is a bug in `next-connect` that causes a possible memory leak. This is a troubling one because from the outside, there would not be any error (API responses will still be served normally to incoming requests)

The promise created by calling `handler(req, res)` (usually by Next.js internally at https://github.com/vercel/next.js/blob/1c1a4de0e2d38090fcf95ef0a6f6790006aaa124/packages/next/server/api-utils.ts#L108) will never be able to resolve, causing the logic from there onward to not be executable.

Normally, a forever-pending promise does not cause an issue. However, since it makes use of references of `request` and `response`, it prevents GC from recycling those in memory, creating memory leaks as requests come in.

### PR DESCRIPTION
**Pull request by hoangvvo**
There was a bug that prevent `await handler(req, res)` to be finished. This aims to solve it by resolving when `end` event is called in response object.

It is possible to disable this behavior (to resolve immediately) using `options.disableResponseWait`.

Fixed #179

### CODE REVIEW

**Comment by hoangvvo** [comment]
Published as `beta` for testing:

```
npm i next-connect@beta
```

File: src/index.js [hunk 1]
```diff
@@ -9,13 +9,21 @@ export default function factory({
...
   attachParams = false,
+  disableResponseWait = false,
 } = {}) {
-  function nc(req, res) {
+  async function nc(req, res) {
+    let closeP;
+    if (!disableResponseWait && "once" in res)
+      closeP = new Promise((resolve) => {
+        res.once("close", resolve);
+        if (isResSent(res)) resolve();
```
Comment (jakeorr) [inline src/index.js:19]: I'm seeing this setup happening before my route code executes, and at that point the response hasn't been sent. I'm not sure this line does anything.

**Comment by jakeorr** [comment]
This is what I'm testing with:

index.page.js
```js
const handler = nc({ onError })
  .get((req, res) => {
    res.status(200).send('hello!');
  })
```

index.test.js
```js
test('resolves', async () => {
  const { req, res } = createMocks({ method: 'GET', url: '/' });
  await handler(req, res);
});
```

Using the changes in this PR, my test's handler call is not resolving and the test times out. Maybe I'm not understanding when the "close" event occurs. Looking at your change, I think I should expect the close event to fire and the handler to resolve, please correct me if I'm wrong here.

Interestingly, if I use the `disableResponseWait: true` option, the handler resolves and my test completes successfully. In this case it seems like the only thing that changed is that the `nc` function now returns a promise (from the `async function` change).

There might be something here I'm not understanding. Is this the intended behaviour?

**Comment by jakeorr** [comment]
To answer one of my questions; from `node-mocks-http`:

> NOTE: The out-of-the-box mock event emitter included with node-mocks-http is not a functional event emitter and as such does not actually emit events. If you wish to test your event handlers you will need to bring your own event emitter.

So it's not emitting the event. As a note, when give the mock response an event emitter as shown [here](https://github.com/howardabrams/node-mocks-http#createresponse), it emits "end", but not "close".

**Comment by hoangvvo** [comment]
> To answer one of my questions; from `node-mocks-http`:
> 
> > NOTE: The out-of-the-box mock event emitter included with node-mocks-http is not a functional event emitter and as such does not actually emit events. If you wish to test your event handlers you will need to bring your own event emitter.
> 
> So it's not emitting the event. As a note, when I give the mock response an event emitter as shown [here](https://github.com/howardabrams/node-mocks-http#createresponse), it emits "end", but not "close".

According to Node document, it emits the "close" event https://nodejs.org/api/http.html#event-close_1. My unit test using super test (which spins up a server) confirms this (see Changes). My thought is that node-mocks-http misses out on the "close" event.

But I'm okay to switch it to "end" too, but just need to make sure the event is always called as long as we "end" the response.

**Comment by hoangvvo** [comment]
> Interestingly, if I use the `disableResponseWait: true` option, the handler resolves and my test completes successfully. In this case it seems like the only thing that changed is that the `nc` function now returns a promise (from the `async function` change).

On a side note, about this point, in both the old and new version, the function returns a promise. But the old one has a bug that prevents the promise from being resolved (#179).

When disableResponseWait is true, the promise resolved immediately (even before request middleware finish running). Only the above the test (which does not assert anything) works. If you asserts headers, body, etc, it will end up incorrectly.

File: src/index.js (hunk 1 above)
Comment (hoangvvo) [reply src/index.js:19]: There might be a chance that the user finishes the response before actually using our handler. It's definitely rare, but I just add the check for completion.

```js
const handler = nc();

export default function (req, res) {
   res.end();
   await handler(req,res);
}

```

**Comment by jakeorr** [comment]
Thanks for sharing all the details. What you talked about above make sense. I agree that under normal circumstances listening to the request "close" event would be fine. It would be nice for this change to listen on the "end" event just to have it work with node-mocks-http, as long as that doesn't cause other issues. I opened an issue to see what the maintainers think about emitting "close".

**Comment by hoangvvo** [comment]
> Thanks for sharing all the details. What you talked about above make sense. I agree that under normal circumstances listening to the request "close" event would be fine. It would be nice for this change to listen on the "end" event just to have it work with node-mocks-http, as long as that doesn't cause other issues. I opened an issue to see what the maintainers think about emitting "close".

For your reference, `light-my-request`, the HTTP mocking API (also no server) used in the popular library `fastify`, also emit the `close` event: https://github.com/fastify/light-my-request/blob/master/lib/response.js#L98-L107

There is also a comment here that mention: https://github.com/fastify/light-my-request/blob/46781cc6cf826d3c2fc0494b07a02395125a7fbf/lib/response.js#L92-L93

```
  // We need to emit 'close' otherwise stream.finished() would
  // not pick it up on Node v16
```

Nearby them, however, there is a [`finish`](https://nodejs.org/api/http.html#event-finish) event, which seems to be a good candidate too since this event is always fired afaik:

https://github.com/fastify/light-my-request/blob/master/lib/response.js#L90
```javascript
Response.prototype.end = function (data, encoding, callback) {
  if (data) {
    this.write(data, encoding)
  }

  http.ServerResponse.prototype.end.call(this, callback)

  this.emit('finish')

  // We need to emit 'close' otherwise stream.finished() would
  // not pick it up on Node v16

  this.destroy()
}
```

**Comment by hoangvvo** [comment]
Looks like `node-mocks-http` support `finish` event too: https://github.com/howardabrams/node-mocks-http/blob/master/lib/mockResponse.js#L472. This one might be better altogether.

**Comment by jakeorr** [comment]
Nice, yeah finish works for me too. Seems like a good change! I'm happy with how this is looking.

File: src/index.js [hunk 2]
```diff
@@ -9,13 +9,21 @@ export default function factory({
   onError = onerror,
   onNoMatch = onerror.bind(null, { status: 404, message: "not found" }),
   attachParams = false,
+  disableResponseWait = false,
 } = {}) {
-  function nc(req, res) {
+  async function nc(req, res) {
+    let closeP;
```
Comment (jakeorr) [inline src/index.js:15]: Minor thing, but this could be called `finishP` now. Would be a bit more readable.

**Review by jakeorr — APPROVED** [review]

**Comment by hoangvvo** [comment]
Thanks for the review @jakeorr. I really appreciate it! Will create a release soon after this.
